[package]
authors = ["Joep Meindertsma <joep@ontola.io>"]
description = "Create, share and model Atomic Data with this graph database server."
edition = "2021"
license = "MIT"
name = "atomic-server"
repository = "https://github.com/joepio/atomic-data-rust"
version = "0.29.2"
[[bin]]
name = "atomic-server"
path = "src/bin.rs"

[dependencies]
actix = "0.12.0"
actix-cors = "0.6.0-beta.4"
actix-files = "0.6.0-beta.9"
actix-web-actors = "4.0.0-beta.7"
actix-web-static-files = "3"
chrono = "0.4.19"
dirs = "3.0.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.16"
log = "0.4.11"
promptly = "0.3.0"
regex = "1.4.2"
rio_api = "0.6.1"
rio_turtle = "0.6.1"
rustls-pemfile = "*"
serde_json = "1.0.60"
static-files = "0.2.1"
sysinfo = "0.20.5"
tantivy = "0.16.1"

[build-dependencies]
static-files = "0.2.1"

[dependencies.acme-lib]
optional = true
version = "0.8.1"

[dependencies.actix-web]
features = ["rustls"]
version = "4.0.0-beta.12"

[dependencies.atomic_lib]
features = ["config", "db", "rdf"]
path = "../lib"
version = "0.29.2"

[dependencies.clap]
features = ["derive", "env"]
version = "3.0.0-rc.3"

[dependencies.open]
optional = true
version = "2.0.1"

[dependencies.rustls]
optional = true
version = "0.20.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.118"

[dependencies.tokio]
features = ["time"]
version = "1.14.0"

[dependencies.tray-item]
optional = true
version = "0.6.0"

[dev-dependencies]
actix-rt = "2.4.0"

[features]
default = ["https"]
desktop = ["tray-item", "open"]
https = ["acme-lib", "rustls"]

[lib]
name = "atomic_server_lib"
path = "src/lib.rs"
