[package]
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"
name = "example-plugin"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
atomic-bindings = {path = "../bindings/rust-plugin"}
time = {version = "0.3", features = ["serde-human-readable"]}
